### ISSUE TITLE
Creation of new repo for the MQ CLI plugin/extension

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/zac#125]
A new CLI extension for Zowe has been created. The IBM MQ team are happy with it being released as v1.0. The repo is currently waiting in a private location ready for the go-ahead to put it into zowe github and subsequently publishing to bintray

I expect we want to review it from a conformance/compliance perspective but we can only really do that once it is on zowe GitHub.

So can I put it on Zowe GitHub?
Developer is myself Colin Stone.

**Comment by armstro** [comment]
I am going to need @nkocsis or @markto comment because I think we had a similar situation recently with the IMS REST API contribution. As I recall IMS had their code in an IBM repo and needed to follow the IBM OSSC rules for external contribution. Once that was done it was moved to a "temp" repo for Linux Foundation scan before being placed in a Zowe github repo. (There is a separate issue for how to track the LF scans historically but I assume that is not a blocker to getting the MQ CLI plug in checked in.)

**Comment by Colin-Stone** [comment]
In the mean time the CLI squad are reviewing from a compliance and conformance perspective. The repo is in a temp repo for that

**Comment by MarkAckert** [comment]
I have reached out to schedule the repository for scan, and as this repository will be a CLI plugin & therefore CLI subproject - my understanding is the ZLC will not need to vote on this to bring it into the zowe org. I will track the progress of the repository migration here.

**Comment by MarkAckert** [comment]
This is completed
