### ISSUE TITLE
Zowe Testing - Multiple z/OS versions

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#144]
How should the community go about testing or validating Zowe on different z/OS versions, or zNext?

**Comment by armstro** [comment]
My opinion: Since both the specifics of new z/OS releases and new Z 
hardware is not public information until day of announce - I think it is 
up to the contributing Zowe open community members to test under whatever 
NDA agreements they have with IBM and then on day of announce, disclose 
what testing they have done. While individuals may not have agreements in 
place for early access to unannounced z/OS releases or new Z hardware, 
software vendors typically have access through IBM ISV support programs. 

It would be interesting to know how Linux Foundation handles similar 
situations - I assume there are open project that gain access to 
unannounced hardware other than Z and must have some legal process to 
follow? Once we have a vendor neutral build/test environment, I assume 
Zowe team (with proper legal agreements in place) could participate in 
early z/OS software and hardware programs like any other organization. 

 
Bruce Armstrong 
IBM System Z Offering Manager- zowe.org 
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: armstrob@us.ibm.com
Tel: 919-254-8773
Cell: 919-931-3132

**Comment by hogstrom** [comment]
Mark Ackert
Jack Jia
Joe Winchester
Nick

**Comment by MarkAckert** [comment]
We now have multiple versions of z/OS to test against. For future z/OS versions, it continues to be the community's responsibility to coordinate with our z/OS systems providers to build out the proper images.
