### ISSUE TITLE
How to Strengthen Squads - Diversity, Metrics, Mentoring ....

### ISSUE THREAD

**Issue by armstro** [zowe/zac#179]
Review diversity on the squads and look at ways to strengthen - how best to measure? - mentor programs?

**Comment by PeterFandelAtRocket** [comment]
Measure:  Commits by "minority" committers where minority means a committer from an organization not the organization of the majority of committers (a mouthful but you know what I mean).
Mentorship: An agreement between mentor and mentee with commitments.  Mentor is an experienced committer in a squad.  Mentee is a would be minority committer.  Mentor commits to take the time to introduce mentee to code base, answer questions, and guide through initial educational work assignments.  Mentee commits to mentor to devote real time (minimum hours per week).  Commitments required because mentors will only be able to mentor a small (1? 2?) number of mentees at any given moment.
...not sure how formal this should be?
Tutorials present as a prerequisite?

**Comment by armstro** [comment]
[Zowe Squad Diversity - Draft  .pptx](https://github.com/zowe/zlc/files/4540985/Zowe.Squad.Diversity.-.Draft.pptx)

Initial thoughts in ppt format

**Comment by solsu01** [comment]
@armstro what do you mean by "Any CII badge that applies?" - are you asking if there's a diversity badge from CII?

**Comment by armstro** [comment]
@solsu01 The proposed list of goals is beyond just diversity (and we need to define the term) so I am "fishing" for ideas on how "health of a squad" can be measured. In my mind it is not just diversity of the squad (people from different orgs) but could also mean the "maturity" of the squad, number of people, etc. and thought there might be some metric we could find from some other community like CII.....is there a badge for members to earn as indication of "health"? For example, being SAFe agile practitioners, secure engineering badges, maybe reviewer and committers be from different organizations, etc.

**Comment by jmertic** [comment]
Great idea. It seems from the slides that the initial focus is organization diversity, which likely makes sense. You might also over time want to expand to age and gender, but that data is really tough to collect in aggregate without violating personal privacy regulations. 

I think it would be helpful to group repos to squads so we could get a better view on how this looks today - any chance y'all could put this together so I can then get it modeled at https://lfanalytics.io/projects/open-mainframe-project%2Fzowe/dashboard to better review.

**Comment by armstro** [comment]
ZLC opinion was diversity situation has improved over the last two PIs - decision was to close this item and reopen if/when issue resurfaces.
