### ISSUE TITLE
Zowe seems "closed" with meetings and recordings

### ISSUE THREAD

**Issue by solsu01** [zowe/zac#189]
Feedback on the Zowe Explorer squad kick off was that Zowe seems a bit closed with meetings and recordings. @phaumer are you able to share specifics on which artifacts are difficult to access? We would like to use your feedback to make accessibility better/more open.

**Comment by armstro** [comment]
Just a theory regarding the impression of closed meetings - due to recent Zoom hacking incidents the OMP tighten access to use of Zoom - I think everyone requires a Zoom account at a minimum - this may give an impression the meetings are not as open as they once were. I think those of use who attend meetings forget our userids are embedded in browsers or Zoom client and don't realize new participants may be presented with userid and password prompts.

**Comment by phaumer** [comment]
Yes, I was hoping that recordings could be provided to the public without the need to sign up with Zoom, which seems an inhibitor, because of their reputation.

Also finding the recording is not easy. When you enter the https://github.com/zowe/community repo you see the `Playbacks/Meeting Minutes and Recordings` right at the top, but that folder is not used anymore. A clean-up would be good so that it is intuitive to find things.

Teams were also using Google docs or sometime Word docs in Box to share notes in the past that required access. 

Perhaps a portal page on zowe.org that provides navigation to each squad's collateral would be good. There should a canonical way to find all wikis, docs, and recordings for CLI vs Web UI vs ML etc. that would increase transparency for the occasional observer of the project.

**Comment by armstro** [comment]
@phaumer we would like to close this issue if you agree - we think we have improved publishing meeting calendars (yes a Zoom account may be needed for security reasons) .....we do understand that logging of recordings is not consistent across squads and improvement is needed. We will ask the squads to improve - especially when requested by community members (due to time zone issues).
