### ISSUE TITLE
How to acclerate adoption of PSI for Zowe distribution 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#223]
Request to add PSI (newer z/OS distribution file format) to Zowe code (currently Pax and SMP/E)

**Comment by pdubz3** [comment]
I had some internal discussions about this to figure out what might be the best path forward.  The Broadcom team might have the resources and some automation in place that would enable testing of a sample Zowe PSI, to validate the concept and identify any significant obstacles.  I'll get some estimates to see if that can be done.  But ultimately, in order to support the PSI format in Zowe, we need to create some stories on our backlog to build some automation for it, and it might need to be planned for next PI.  Between now and then we can do some research and grooming to make sure we're ready.  Again, we can leverage some expertise on the Broadcom side.  I know that IBM also has some expertise in this area but possibly not as close to the Zowe team as the folks at Broadcom.

**Comment by armstro** [comment]
Being worked as part of this PI Planning interval - closing this item
