### ISSUE TITLE
Provide a code ready workspace environment for testing Zowe Explorer

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zac#224]
@Joe-Winchester commented on [Fri Mar 05 2021](https://github.com/zowe/community/issues/1066)

Some features of Zowe Explorer, such as Secure Credentials Plugins, are problematic to install and configure in a code ready workspace.  This creates issues for upstream offerings that deploy Zowe Explorer.

To debug and diagnose these issues it'd be good if there was a code ready workspace available for the Zowe Explorer and CLI squads to work with.  

This came up on a call where the Zowe Explorer squad and Db2 Developer Extensions for z/OS were talking about futures

**Comment by armstro** [comment]
Adding Mike to this requirement as resolution may require some vendor cooperation - this requirement has existed since late 2020. There does not appear to be a public/free Red Hat Code Ready Workspace environment for testing but research into this has not been exhaustive.  IBM has a commercial offering (Wazi) that does do IBM internal testing that includes Zowe Explorer. It is assumed (to be confirmed) if problems occur that the community would be notified.

**Comment by armstro** [comment]
One possible lead: https://developers.redhat.com/developer-sandbox

**Comment by pdubz3** [comment]
Spoke with Mike Bauer following the ZAC meeting today and he feels that this is not urgent and can be closed until the becomes urgent.
