### ISSUE TITLE
ZAC input to incubator criteria 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#227]
What criteria do we look for in an incubator proposal - process here https://github.com/zowe/zlc/blob/master/process/proposal_process.md (but this should be moving over to TSC) 

_Starter set_ from ZAC 
- Consistent with the Zowe principles (when published) - good for platform/ecosystem, ... 
- Appeals to Next Gen IT Staff - forward looking technologies 
- Existing or potential integration with one or more Zowe core (examples: one or more REST APIs, Desktop, CLI or VS Code) 
- Some development resource (in addition to code) - even if part time - to enhance, integrate, educate, advocate the code OR expected to attract dev resource with assistance from OMP and Zowe community 
-

**Comment by PeterFandelAtRocket** [comment]
Good start. Can't think of more now. Let's discuss in next ZAC mtg.

**Comment by pdubz3** [comment]
"Consistent with Zowe **vision and principles**".  And presumably, that already checks the box for "good for platform" otherwise we've done a poor job on the vision and principles.  :-)  I also think "appeals to next gen" should be in the vision (see my earlier comments in #228).     

"Existing or potential integration with one or more Zowe core (examples: one or more REST APIs, Desktop, CLI or VS Code)" ... you might want to add "or has the potential to extend Zowe by introducing a new core component".  I believe that's still possible, I hope I'm not alone.  

At some point I think we need to establish a requirement that some set of success criteria be established up front.  What is the goal of the incubator?  How will we know that we've succeeded?  How can we know that it's failed?  How much capacity will be required?  And for how long?  Do these things belong in this document or somewhere else?

I think this also includes how the incubator would operate within the Zowe community at maturity, if it succeeds.  Would it make sense to operate as a separate squad?  Or would it become part of an existing squad?  Or might it even create a change in our existing squad structure?

**Comment by pdubz3** [comment]
This is complete.
