### ISSUE TITLE
Certificate Strategy

### ISSUE THREAD

**Issue by hogstrom** [zowe/zac#27]
Management

We need to document the certs we are shipping, where they are located and their expiration date

**Comment by hogstrom** [comment]
Could use Let's Encrypt as a way of installing.

**Comment by 1000TurquoisePogs** [comment]
The certs for the UI portion are located within https://github.com/zowe/zlux-example-server/tree/master/config
As the name suggests, the example server is an implementation of the server. It could be renamed to something better to state it's "zowe default" nature, but regardless this is where we keep certs and keys for HTTPS. They're just self-signed.
Since lets encrypt allows for free signed certs as a result of you proving that your host is legitimate, we can't put lets encrypt certs in the git repo but our installer could prompt the user as to:
1. whether they'd like to provide their own certs (and point to where they are),
2. if they'd like to go through the lets encrypt option (I believe it requires an internet connection, so not everyone can do this)
3. use the shipped self-signed certs

**Comment by 1000TurquoisePogs** [comment]
I found acme.sh and greenlock to be the two most promising tools that work with Let's Encrypt (really, an implementer of the ACME protocol).
acme.sh didn't work on the mainframe.
greenlock as a stand-alone tool expects the network ports to be 443 and 80.
So my latest idea is to use greenlock-express as a library to make a small custom nodejs server that runs as a small tool for a few seconds to generate a valid HTTPS cert that I assume could then be copied into a place that is usable by all of our servers.

There's still one big problem with all of this: Let's Encrypt is designed for internet-connected servers, because a server proves its legitimacy by showing that the publicly accessible server is under your control. This doesn't seem like it will help LAN access which is our common use case.

**Comment by hogstrom** [comment]
I have the same problem with my servers … they can access the Internet but the Internet cannot access them.  I suspect all customers have faced this issue though and already have certs … anyone have first hand knowledge?   We could ask on the on boarding channel and ask users that have deployed Zowe what their approach is ?

Matt Hogstrom
matt@hogstrom.org
+1-919-656-0564
PGP Key: 0x90ECB270
Facebook <https://www.facebook.com/matt.hogstrom>  LinkedIn <https://linkedin.com/in/mhogstrom>  Twitter <https://twitter.com/hogstrom>

From Lord of the Rings, when Frodo decides to leave the Fellowship and go to Mordor alone . . . Frodo:  “I wish the ring had never come to me.  I wish none of this had happened.”  Gandalf:  “So do all who live to see such things.  But it is not for them to decide.  All you have to do is decide what to do with this time that is given to you.”

**Comment by hogstrom** [comment]
My thoughts here are we should have all services that are shipped as part of Zowe use the same self-signed certificate which should be a project wide resource.  We could try and provide an easy button for certs but the reality is that all mainframe customers have their own process for managing and adding certs so the work we do here is probably only useful to a small number of people.  Thoughts ?  I suggest we go with a single self-signed cert (we can put it in the CI/CD repo) and move on for now.

**Comment by 1000TurquoisePogs** [comment]
Update: ZLC voted on that it would be time better spent to focus on making it easy to apply 1 certificate to all of zowe for ease of allowing users to provide their own signed certs. The default (self-signed) cert could be this one, since it's valid for 2 years and says "Zowe": 
https://github.com/zowe/zlux-example-server/blob/master/config/server.key
https://github.com/zowe/zlux-example-server/blob/master/config/server.cert

**Comment by hogstrom** [comment]
Moving to CI/CD and assigning it to @jackjia-ibm

**Comment by hogstrom** [comment]
This issue was moved to zowe/release-management#2
